
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `AppDb`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=localhost;Database=test;User Id=test;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace AppDb
{
	[Alias("T05")]
	[Schema("dbo")]
    public partial class T05 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("ModelIntValue")]
	[Schema("dbo")]
    public partial class ModelIntValue : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public int? Value { get; set;}
        public string Text { get; set;}
        [Required]
        public long LongMismatch { get; set;}
        public int? LongMismatch2 { get; set;}
    }
	[Alias("Product")]
	[Schema("dbo")]
    public partial class Product : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string Name { get; set;}
        [Required]
        public decimal UnitPrice { get; set;}
    }
	[Alias("Fortune")]
	[Schema("dbo")]
    public partial class Fortune : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string message { get; set;}
    }
	[Alias("T06")]
	[Schema("dbo")]
    public partial class T06 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("DbPoco")]
	[Schema("dbo")]
    public partial class DbPoco : IHasId<string> 
    {
        [Alias("Id_primary")]
        [Required]
        public string Id { get; set;}
        public string Other_Id { get; set;}
    }
	[Alias("Customer")]
	[Schema("dbo")]
    public partial class Customer : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string FirstName { get; set;}
        public string LastName { get; set;}
        public string Email { get; set;}
        public string PhoneNumbers { get; set;}
        public string Addresses { get; set;}
        [Required]
        public DateTime CreatedAt { get; set;}
    }
	[Alias("DateTimeObject")]
	[Schema("dbo")]
    public partial class DateTimeObject : IHasId<DateTime> 
    {
        [Alias("Test")]
        [Required]
        public DateTime Id { get; set;}
    }
	[Alias("T07")]
	[Schema("dbo")]
    public partial class T07 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("Note")]
	[Schema("dbo")]
    public partial class Note : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string SchemaUri { get; set;}
        public string NoteText { get; set;}
        public DateTime? LastUpdated { get; set;}
        public string UpdatedBy { get; set;}
    }
	[Alias("ModelWithCompositeIndexFields")]
	[Schema("dbo")]
    public partial class ModelWithCompositeIndexField : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        public string Name { get; set;}
        public string AlbumId { get; set;}
        public string UniqueName { get; set;}
        public string Composite1 { get; set;}
        public string Composite2 { get; set;}
    }
	[Alias("Order")]
	[Schema("dbo")]
    public partial class Order : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int CustomerId { get; set;}
        [Required]
        public int EmployeeId { get; set;}
        public string ShippingAddress { get; set;}
        public DateTime? OrderDate { get; set;}
        public DateTime? RequiredDate { get; set;}
        public DateTime? ShippedDate { get; set;}
        public int? ShipVia { get; set;}
        [Required]
        public decimal Freight { get; set;}
        [Required]
        public decimal Total { get; set;}
    }
	[Alias("T08")]
	[Schema("dbo")]
    public partial class T08 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("ModelWithIndexFields")]
	[Schema("dbo")]
    public partial class ModelWithIndexField : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        public string Name { get; set;}
        public string AlbumId { get; set;}
        public string UniqueName { get; set;}
    }
	[Alias("Shipper")]
	[Schema("dbo")]
    public partial class Shipper : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string CompanyName { get; set;}
        public string Phone { get; set;}
        [Required]
        public int ShipperTypeId { get; set;}
    }
	[Alias("T09")]
	[Schema("dbo")]
    public partial class T09 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("ModelWithNamedCompositeIndex")]
	[Schema("dbo")]
    public partial class ModelWithNamedCompositeIndex : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        public string Name { get; set;}
        public string AlbumId { get; set;}
        public string UniqueName { get; set;}
        public string Composite1 { get; set;}
        public string Composite2 { get; set;}
    }
	[Alias("OrderDetail")]
	[Schema("dbo")]
    public partial class OrderDetail : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int OrderId { get; set;}
        [Required]
        public int ProductId { get; set;}
        [Required]
        public decimal UnitPrice { get; set;}
        [Required]
        public int Quantity { get; set;}
        [Required]
        public decimal Discount { get; set;}
    }
	[Alias("Manufacturer")]
	[Schema("dbo")]
    public partial class Manufacturer : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("T10")]
	[Schema("dbo")]
    public partial class T10 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("Addresses")]
	[Schema("dbo")]
    public partial class Address : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        public string City { get; set;}
        public string Countryalias { get; set;}
    }
	[Alias("TableName")]
	[Schema("dbo")]
    public partial class TableName : IHasId<int> 
    {
        [Alias("TableId")]
        [Required]
        public int Id { get; set;}
        [Required]
        public long Long { get; set;}
        [Required]
        public Guid Guid { get; set;}
    }
	[Alias("T11")]
	[Schema("dbo")]
    public partial class T11 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("table_alias")]
	[Schema("dbo")]
    public partial class table_alias : IHasId<string> 
    {
        [Alias("id")]
        [Required]
        public string Id { get; set;}
        public string column_alias { get; set;}
        public string album_id { get; set;}
        public string album_name { get; set;}
    }
	[Alias("TaskQueue")]
	[Schema("dbo")]
    public partial class TaskQueue : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public Guid? UserId { get; set;}
        public string Task { get; set;}
        public string ContentUrn { get; set;}
        public string Status { get; set;}
        [Required]
        public DateTime CreatedDate { get; set;}
        [Required]
        public int Priority { get; set;}
        [Required]
        public int NoOfAttempts { get; set;}
        public string ErrorMessage { get; set;}
    }
	[Alias("Hello")]
	[Schema("dbo")]
    public partial class Hello : IHasId<string> 
    {
        [Alias("Name")]
        [Required]
        public string Id { get; set;}
    }
	[Alias("ModelWithRowVersionBase")]
	[Schema("dbo")]
    public partial class ModelWithRowVersionBase : IHasId<long> 
    {
        public string MoreData { get; set;}
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set;}
        public string Text { get; set;}
        [Required]
        public byte[] RowVersion { get; set;}
    }
	[Alias("Child")]
	[Schema("dbo")]
    public partial class Child : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string Value { get; set;}
    }
	[Alias("ModelWithRowVersion")]
	[Schema("dbo")]
    public partial class ModelWithRowVersion : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set;}
        public string Text { get; set;}
        [Required]
        public byte[] RowVersion { get; set;}
    }
	[Alias("Parent")]
	[Schema("dbo")]
    public partial class Parent : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public int? ChildId { get; set;}
    }
	[Alias("Activity")]
	[Schema("dbo")]
    public partial class Activity : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string ActivityType { get; set;}
        public string Comment { get; set;}
    }
	[Alias("ModelWithRowVersionAlias")]
	[Schema("dbo")]
    public partial class ModelWithRowVersionAlias : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set;}
        public string Text { get; set;}
        [Required]
        public byte[] VersionAlias { get; set;}
    }
	[Alias("TestRowVersion")]
	[Schema("dbo")]
    public partial class TestRowVersion : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
        [Required]
        public byte[] RowVersion { get; set;}
    }
	[Alias("Movie")]
	[Schema("dbo")]
    public partial class Movie : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        public string Title { get; set;}
        [Required]
        public decimal Rating { get; set;}
        public string Director { get; set;}
        [Required]
        public DateTime ReleaseDate { get; set;}
        public string TagLine { get; set;}
        public string Genres { get; set;}
    }
	[Alias("TestType")]
	[Schema("dbo")]
    public partial class TestType : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string TextCol { get; set;}
        [Required]
        public bool BoolCol { get; set;}
        [Required]
        public DateTime DateCol { get; set;}
        [Required]
        public string EnumCol { get; set;}
        public string ComplexObjCol { get; set;}
    }
	[Alias("ModelWithRowVersionAndParent")]
	[Schema("dbo")]
    public partial class ModelWithRowVersionAndParent : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int ModelWithOptimisticChildrenId { get; set;}
        public string Text { get; set;}
        [Required]
        public long Version { get; set;}
    }
	[Alias("ModelWithOptimisticChildren")]
	[Schema("dbo")]
    public partial class ModelWithOptimisticChild : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Text { get; set;}
    }
	[Alias("ReferencedType")]
	[Schema("dbo")]
    public partial class ReferencedType : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("Table2")]
	[Schema("dbo")]
    public partial class Table2 : IHasId<int> 
    {
        [Alias("Key")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Tri { get; set;}
        [Required]
        public int Table1 { get; set;}
    }
	[Alias("TypeWithOnDeleteAndUpdateCascade")]
	[Schema("dbo")]
    public partial class TypeWithOnDeleteAndUpdateCascade : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? RefId { get; set;}
    }
	[Alias("ShipperTypes")]
	[Schema("dbo")]
    public partial class ShipperType : IHasId<int> 
    {
        [Alias("ShipperTypeID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
    }
	[Alias("Tabela1")]
	[Schema("dbo")]
    public partial class Tabela1 : IHasId<int> 
    {
        [Alias("Key")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Ena { get; set;}
    }
	[Alias("NullableActivity")]
	[Schema("dbo")]
    public partial class NullableActivity : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string ActivityType { get; set;}
        public string Comment { get; set;}
    }
	[Alias("Table3")]
	[Schema("dbo")]
    public partial class Table3 : IHasId<int> 
    {
        [Alias("Key")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Tri { get; set;}
        public int? TableTwoKey { get; set;}
    }
	[Alias("PersonWithNullableAutoId")]
	[Schema("dbo")]
    public partial class PersonWithNullableAutoId : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string FirstName { get; set;}
        public string LastName { get; set;}
        [Required]
        public int Age { get; set;}
    }
	[Alias("tab_ModelWithIdAndName")]
	[Schema("dbo")]
    public partial class tab_ModelWithIdAndName : IHasId<int> 
    {
        [Alias("col_Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string col_Name { get; set;}
    }
	[Alias("TypeWithOnDeleteRestrict")]
	[Schema("dbo")]
    public partial class TypeWithOnDeleteRestrict : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? RefId { get; set;}
    }
	[Alias("Tabela2")]
	[Schema("dbo")]
    public partial class Tabela2 : IHasId<int> 
    {
        [Alias("Key")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Tri { get; set;}
        [Required]
        public int Tabela1 { get; set;}
    }
	[Alias("CustomerAddress")]
	[Schema("dbo")]
    public partial class CustomerAddress : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int CustomerId { get; set;}
        public string AddressLine1 { get; set;}
        public string AddressLine2 { get; set;}
        public string City { get; set;}
        public string State { get; set;}
        public string Country { get; set;}
    }
	[Alias("tab_ModelWithFieldsOfDifferentTypes")]
	[Schema("dbo")]
    public partial class tab_ModelWithFieldsOfDifferentType : IHasId<int> 
    {
        [Alias("col_Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string col_Name { get; set;}
        [Required]
        public long col_LongId { get; set;}
        [Required]
        public Guid col_Guid { get; set;}
        [Required]
        public bool col_Bool { get; set;}
        [Required]
        public DateTime col_DateTime { get; set;}
        [Required]
        public double col_Double { get; set;}
    }
	[Alias("Country")]
	[Schema("dbo")]
    public partial class Country : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string CountryName { get; set;}
        public string CountryCode { get; set;}
    }
	[Alias("TypeWithOnDeleteSetDefault")]
	[Schema("dbo")]
    public partial class TypeWithOnDeleteSetDefault : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int RefId { get; set;}
    }
	[Alias("Baz")]
	[Schema("dbo")]
    public partial class Baz : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
    }
	[Alias("MultipleConnection")]
	[Schema("dbo")]
    public partial class MultipleConnection : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set;}
        public string Data { get; set;}
    }
	[Alias("ModelAliasWithSpace")]
	[Schema("dbo")]
    public partial class ModelAliasWithSpace : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Alias("The Name")]
        public string The_Name { get; set;}
    }
	[Alias("LetterStat")]
	[Schema("dbo")]
    public partial class LetterStat : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public long LetterFrequencyId { get; set;}
        public string Letter { get; set;}
        [Required]
        public int Weighting { get; set;}
    }
	[Alias("Order2")]
	[Schema("dbo")]
    public partial class Order2 : IHasId<int> 
    {
        [Alias("ID")]
        [Required]
        public int Id { get; set;}
        public int? CustomerID { get; set;}
    }
	[Alias("Band")]
	[Schema("dbo")]
    public partial class Band : IHasId<string> 
    {
        [Alias("Name")]
        [Required]
        public string Id { get; set;}
        [Required]
        public int PersonId { get; set;}
    }
	[Alias("BarJoin")]
	[Schema("dbo")]
    public partial class BarJoin : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public string Name { get; set;}
    }
	[Alias("ModelWithIdAndName")]
	[Schema("dbo")]
    public partial class ModelWithIdAndName : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("OrderItem2")]
	[Schema("dbo")]
    public partial class OrderItem2 : IHasId<int> 
    {
        [Alias("ID")]
        [Required]
        public int Id { get; set;}
        public int? Order2Id { get; set;}
        public string ProductID { get; set;}
    }
	[Alias("Entity1")]
	[Schema("dbo")]
    public partial class Entity1 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string COL_A { get; set;}
    }
	[Alias("TypeWithOnDeleteSetNull")]
	[Schema("dbo")]
    public partial class TypeWithOnDeleteSetNull : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? RefId { get; set;}
    }
	[Alias("ModelWithGuidPK")]
	[Schema("dbo")]
    public partial class ModelWithGuidPK : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public long Long { get; set;}
    }
	[Alias("FooBar")]
	[Schema("dbo")]
    public partial class FooBar : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public Guid fkBarId { get; set;}
    }
	[Alias("tab_Users")]
	[Schema("dbo")]
    public partial class tab_User : IHasId<int> 
    {
        [Alias("col_Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string col_Name { get; set;}
        [Required]
        public int col_Age { get; set;}
    }
	[Alias("TableA")]
	[Schema("dbo")]
    public partial class TableA : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public bool Bool { get; set;}
    }
	[Alias("TypeWithSimpleForeignKey")]
	[Schema("dbo")]
    public partial class TypeWithSimpleForeignKey : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int RefId { get; set;}
    }
	[Alias("TableB")]
	[Schema("dbo")]
    public partial class TableB : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int TableAId { get; set;}
        public string Name { get; set;}
    }
	[Alias("FooBarBaz")]
	[Schema("dbo")]
    public partial class FooBarBaz : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int fkFooBarId { get; set;}
        [Required]
        public int fkBazId { get; set;}
        [Required]
        public decimal Amount { get; set;}
    }
	[Alias("TypeWithOnDeleteCascade")]
	[Schema("dbo")]
    public partial class TypeWithOnDeleteCascade : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? RefId { get; set;}
    }
	[Alias("TypeWithTimeSpan")]
	[Schema("dbo")]
    public partial class TypeWithTimeSpan : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public long TimeSpan { get; set;}
    }
	[Alias("Q_Customer")]
	[Schema("dbo")]
    public partial class Q_Customer : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("Can_use_nested_transactions_Table1")]
	[Schema("dbo")]
    public partial class Can_use_nested_transactions_Table1 : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public DateTime Dummy { get; set;}
    }
	[Alias("Can_use_nested_transactions_Table2")]
	[Schema("dbo")]
    public partial class Can_use_nested_transactions_Table2 : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public DateTime Dummy { get; set;}
    }
	[Alias("CountTestTable")]
	[Schema("dbo")]
    public partial class CountTestTable : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string StringValue { get; set;}
        public int? CountColumn { get; set;}
    }
	[Alias("MigrateSqlServerTypes")]
	[Schema("dbo")]
    public partial class MigrateSqlServerType : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public DateTime? SqlServerTime { get; set;}
        public int? OrmLiteTicks { get; set;}
        public long? OrmLiteTimeSpan { get; set;}
    }
	[Alias("CompositeKey")]
	[Schema("dbo")]
    public partial class CompositeKey 
    {
        [Required]
        public long SubId1 { get; set;}
        [Required]
        public long SubId2 { get; set;}
        public string Data { get; set;}
    }
	[Alias("PocoTable")]
	[Schema("dbo")]
    public partial class PocoTable : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string CharColumn { get; set;}
        public decimal? DecimalColumn { get; set;}
    }
	[Alias("ModelWithSeedDataSql")]
	[Schema("dbo")]
    public partial class ModelWithSeedDataSql : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("ModelWithOnlyStringFields")]
	[Schema("dbo")]
    public partial class ModelWithOnlyStringField : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        public string Name { get; set;}
        public string AlbumId { get; set;}
        public string AlbumName { get; set;}
    }
	[Alias("SampleOrderLine")]
	[Schema("dbo")]
    public partial class SampleOrderLine : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        public string OrderUrn { get; set;}
        [Required]
        public long OrderId { get; set;}
        [Required]
        public long OrderLineId { get; set;}
        [Required]
        public DateTime CreatedDate { get; set;}
        [Required]
        public Guid UserId { get; set;}
        public string UserName { get; set;}
        [Required]
        public Guid ProductId { get; set;}
        public string MflowUrn { get; set;}
        public string ProductType { get; set;}
        public string Description { get; set;}
        public string UpcEan { get; set;}
        public string Isrc { get; set;}
        public Guid? RecommendationUserId { get; set;}
        public string RecommendationUserName { get; set;}
        public string SupplierKeyName { get; set;}
        public string CostTierKeyName { get; set;}
        public string PriceTierKeyName { get; set;}
        [Required]
        public decimal VatRate { get; set;}
        [Required]
        public int ProductPriceIncVat { get; set;}
        [Required]
        public int Quantity { get; set;}
        [Required]
        public decimal TransactionValueExVat { get; set;}
        [Required]
        public decimal TransactionValueIncVat { get; set;}
        [Required]
        public decimal RecommendationDiscountRate { get; set;}
        [Required]
        public decimal DistributionDiscountRate { get; set;}
        [Required]
        public decimal RecommendationDiscountAccruedExVat { get; set;}
        [Required]
        public decimal DistributionDiscountAccruedExVat { get; set;}
        [Required]
        public decimal PromoMix { get; set;}
        [Required]
        public decimal DiscountMix { get; set;}
        [Required]
        public decimal CashMix { get; set;}
        [Required]
        public decimal PromoMixValueExVat { get; set;}
        [Required]
        public decimal DiscountMixValueExVat { get; set;}
        [Required]
        public decimal CashMixValueIncVat { get; set;}
        public string ContentUrn { get; set;}
        public string TrackUrn { get; set;}
        public string Title { get; set;}
        public string ArtistUrn { get; set;}
        public string ArtistName { get; set;}
        public string AlbumUrn { get; set;}
        public string AlbumName { get; set;}
    }
	[Alias("DynamicAttributeSeedData")]
	[Schema("dbo")]
    public partial class DynamicAttributeSeedDatum : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("Contact")]
	[Schema("dbo")]
    public partial class Contact : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Email { get; set;}
        [Required]
        public int Age { get; set;}
        public string Tags { get; set;}
        public string FullName { get; set;}
    }
	[Alias("TestEntity")]
	[Schema("dbo")]
    public partial class TestEntity : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Foo { get; set;}
        public string Bar { get; set;}
        public int? NullInt { get; set;}
        [Required]
        public decimal Baz { get; set;}
    }
	[Alias("ModelWithIdOnly")]
	[Schema("dbo")]
    public partial class ModelWithIdOnly : IHasId<long> 
    {
        [Alias("Id")]
        [Required]
        public long Id { get; set;}
    }
	[Alias("ModelWithComplexTypes")]
	[Schema("dbo")]
    public partial class ModelWithComplexType : IHasId<long> 
    {
        [Alias("Id")]
        [Required]
        public long Id { get; set;}
        public string StringList { get; set;}
        public string IntList { get; set;}
        public string StringMap { get; set;}
        public string IntMap { get; set;}
        public string Child { get; set;}
    }
	[Alias("HasDateTimeOffsetMember")]
	[Schema("dbo")]
    public partial class HasDateTimeOffsetMember : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public DateTimeOffset MomentInTime { get; set;}
    }
	[Alias("WithAListOfGuids")]
	[Schema("dbo")]
    public partial class WithAListOfGuid : IHasId<Guid> 
    {
        [Alias("GuidOne")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public Guid GuidTwo { get; set;}
        public string TheGuids { get; set;}
    }
	[Alias("EntityAttribute")]
	[Schema("dbo")]
    public partial class EntityAttribute : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int EntityId { get; set;}
        [Required]
        public string EntityType { get; set;}
        [Required]
        public string AttributeName { get; set;}
        [Required]
        public string AttributeValue { get; set;}
    }
	[Alias("TestEntityWithAliases")]
	[Schema("dbo")]
    public partial class TestEntityWithAlias : IHasId<int> 
    {
        [Alias("Id Column")]
        [AutoIncrement]
        public int Id { get; set;}
        [Alias("Foo Column")]
        public string Foo_Column { get; set;}
        [Alias("Bar Column")]
        public string Bar_Column { get; set;}
        [Alias("Baz Column")]
        [Required]
        public decimal Baz_Column { get; set;}
    }
	[Alias("HasNullableDateTimeOffsetMember")]
	[Schema("dbo")]
    public partial class HasNullableDateTimeOffsetMember : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public DateTimeOffset? MomentInTime { get; set;}
    }
	[Alias("TestPocoImpl")]
	[Schema("dbo")]
    public partial class TestPocoImpl : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public DateTime DateCreated { get; set;}
        public string Name { get; set;}
    }
	[Alias("DateTimeOffsetObject")]
	[Schema("dbo")]
    public partial class DateTimeOffsetObject : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public DateTimeOffset Test { get; set;}
    }
	[Alias("Unicode_poco")]
	[Schema("dbo")]
    public partial class Unicode_poco : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Text { get; set;}
    }
	[Alias("NullableDateTimeOffsetObject")]
	[Schema("dbo")]
    public partial class NullableDateTimeOffsetObject : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public DateTimeOffset? Test { get; set;}
    }
	[Alias("Location")]
	[Schema("dbo")]
    public partial class Location : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Description { get; set;}
        public string GeoLocation { get; set;}
    }
	[Alias("TypeWithEnumAsInt")]
	[Schema("dbo")]
    public partial class TypeWithEnumAsInt : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public string EnumValue { get; set;}
    }
	[Alias("ModelWithFieldsOfDifferentTypes")]
	[Schema("dbo")]
    public partial class ModelWithFieldsOfDifferentType : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
        [Required]
        public long LongId { get; set;}
        [Required]
        public Guid Guid { get; set;}
        [Required]
        public bool Bool { get; set;}
        [Required]
        public DateTime DateTime { get; set;}
        [Required]
        public double Double { get; set;}
    }
	[Alias("AuditTableA")]
	[Schema("dbo")]
    public partial class AuditTableA : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public DateTime CreatedDate { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
        public string ModifiedBy { get; set;}
    }
	[Alias("UserEntity")]
	[Schema("dbo")]
    public partial class UserEntity : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set;}
        [Required]
        public DateTime Created { get; set;}
        [Required]
        public DateTime Updated { get; set;}
        public DateTime? Deleted { get; set;}
        [Required]
        public bool IsDeleted { get; set;}
    }
	[Alias("DoubleState")]
	[Schema("dbo")]
    public partial class DoubleState : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        [Required]
        public string State1 { get; set;}
        [Required]
        public string State2 { get; set;}
    }
	[Alias("AuditTableB")]
	[Schema("dbo")]
    public partial class AuditTableB : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public DateTime CreatedDate { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
        public string ModifiedBy { get; set;}
    }
	[Alias("AnswerEntity")]
	[Schema("dbo")]
    public partial class AnswerEntity : IHasId<long> 
    {
        [Required]
        public long UserId { get; set;}
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set;}
        [Required]
        public DateTime Created { get; set;}
        [Required]
        public DateTime Updated { get; set;}
        public DateTime? Deleted { get; set;}
        [Required]
        public bool IsDeleted { get; set;}
    }
	[Alias("Author")]
	[Schema("dbo")]
    public partial class Author : IHasId<int> 
    {
        [Alias("AuthorID")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
        [Required]
        public DateTime Birthday { get; set;}
        public DateTime? LastActivity { get; set;}
        [Required]
        public decimal Earnings { get; set;}
        public decimal? NEarnings { get; set;}
        [Required]
        public bool Active { get; set;}
        public string JobCity { get; set;}
        public string Comment { get; set;}
        [Required]
        public int Rate { get; set;}
        public int? NRate { get; set;}
        [Required]
        public double FloatProperty { get; set;}
        public double? NFloatProperty { get; set;}
        [Required]
        public double DoubleProperty { get; set;}
        public double? NDoubleProperty { get; set;}
    }
	[Alias("Todo")]
	[Schema("dbo")]
    public partial class Todo : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set;}
        public string Content { get; set;}
        [Required]
        public int Order { get; set;}
        [Required]
        public bool Done { get; set;}
    }
	[Alias("User")]
	[Schema("dbo")]
    public partial class User : IHasId<long> 
    {
        [Alias("Id")]
        [Required]
        public long Id { get; set;}
        public string Name { get; set;}
        [Required]
        public DateTime CreatedDate { get; set;}
    }
	[Alias("SimpleType")]
	[Schema("dbo")]
    public partial class SimpleType : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("ModelWithLongIdAndStringFields")]
	[Schema("dbo")]
    public partial class ModelWithLongIdAndStringField : IHasId<long> 
    {
        [Alias("Id")]
        [Required]
        public long Id { get; set;}
        public string Name { get; set;}
        public string AlbumId { get; set;}
        public string AlbumName { get; set;}
    }
	[Alias("SimpleAliasedType")]
	[Schema("dbo")]
    public partial class SimpleAliasedType : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string NewName { get; set;}
    }
	[Alias("ModelWithFieldsOfDifferentAndNullableTypes")]
	[Schema("dbo")]
    public partial class ModelWithFieldsOfDifferentAndNullableType : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? NId { get; set;}
        [Required]
        public long LongId { get; set;}
        public long? NLongId { get; set;}
        [Required]
        public Guid Guid { get; set;}
        public Guid? NGuid { get; set;}
        [Required]
        public bool Bool { get; set;}
        public bool? NBool { get; set;}
        [Required]
        public DateTime DateTime { get; set;}
        public DateTime? NDateTime { get; set;}
        [Required]
        public double Float { get; set;}
        public double? NFloat { get; set;}
        [Required]
        public double Double { get; set;}
        public double? NDouble { get; set;}
        [Required]
        public decimal Decimal { get; set;}
        public decimal? NDecimal { get; set;}
        [Required]
        public long TimeSpan { get; set;}
        public long? NTimeSpan { get; set;}
    }
	[Alias("tab_Employee")]
	[Schema("dbo")]
    public partial class tab_Employee : IHasId<int> 
    {
        [Alias("col_Id")]
        [Required]
        public int Id { get; set;}
        public string col_Name { get; set;}
    }
	[Alias("PersonWithAutoId")]
	[Schema("dbo")]
    public partial class PersonWithAutoId : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string FirstName { get; set;}
        public string LastName { get; set;}
        [Required]
        public int Age { get; set;}
    }
	[Alias("ModelWithFieldsOfNullableTypes")]
	[Schema("dbo")]
    public partial class ModelWithFieldsOfNullableType : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public int? NId { get; set;}
        public long? NLongId { get; set;}
        public Guid? NGuid { get; set;}
        public bool? NBool { get; set;}
        public DateTime? NDateTime { get; set;}
        public double? NFloat { get; set;}
        public double? NDouble { get; set;}
        public decimal? NDecimal { get; set;}
        public long? NTimeSpan { get; set;}
    }
	[Alias("tab_Product")]
	[Schema("dbo")]
    public partial class tab_Product : IHasId<int> 
    {
        [Alias("col_Id")]
        [Required]
        public int Id { get; set;}
        public string col_Name { get; set;}
        [Required]
        public decimal col_UnitPrice { get; set;}
    }
	[Alias("Model Alias Space")]
	[Schema("dbo")]
    public partial class Model_Alias_Space : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Alias("The Name")]
        public string The_Name { get; set;}
    }
	[Alias("tab_Customer")]
	[Schema("dbo")]
    public partial class tab_Customer : IHasId<int> 
    {
        [Alias("col_Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string col_FirstName { get; set;}
        public string col_LastName { get; set;}
        public string col_Email { get; set;}
        public string col_PhoneNumbers { get; set;}
        public string col_Addresses { get; set;}
        [Required]
        public DateTime col_CreatedAt { get; set;}
    }
	[Alias("Person")]
	[Schema("dbo")]
    public partial class Person : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("ModelWithIndexer")]
	[Schema("dbo")]
    public partial class ModelWithIndexer : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("tab_Order")]
	[Schema("dbo")]
    public partial class tab_Order : IHasId<int> 
    {
        [Alias("col_Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int col_CustomerId { get; set;}
        [Required]
        public int col_EmployeeId { get; set;}
        public string col_ShippingAddress { get; set;}
        public DateTime? col_OrderDate { get; set;}
        public DateTime? col_RequiredDate { get; set;}
        public DateTime? col_ShippedDate { get; set;}
        public int? col_ShipVia { get; set;}
        [Required]
        public decimal col_Freight { get; set;}
        [Required]
        public decimal col_Total { get; set;}
    }
	[Alias("UserAuth")]
	[Schema("dbo")]
    public partial class UserAuth : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string UserName { get; set;}
        public string Email { get; set;}
        public string PrimaryEmail { get; set;}
        public string FirstName { get; set;}
        public string LastName { get; set;}
        public string DisplayName { get; set;}
        public string Salt { get; set;}
        public string PasswordHash { get; set;}
        public string Roles { get; set;}
        public string Permissions { get; set;}
        [Required]
        public DateTime CreatedDate { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
        public string Meta { get; set;}
    }
	[Alias("ModelWithNumerics")]
	[Schema("dbo")]
    public partial class ModelWithNumeric : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int Byte { get; set;}
        [Required]
        public int SByte { get; set;}
        [Required]
        public int Short { get; set;}
        [Required]
        public int UShort { get; set;}
        [Required]
        public int Int { get; set;}
        [Required]
        public int UInt { get; set;}
        [Required]
        public long Long { get; set;}
        [Required]
        public long ULong { get; set;}
        [Required]
        public double Float { get; set;}
        [Required]
        public double Double { get; set;}
        [Required]
        public decimal Decimal { get; set;}
    }
	[Alias("ModelWithGuid")]
	[Schema("dbo")]
    public partial class ModelWithGuid : IHasId<long> 
    {
        [Alias("Id")]
        [Required]
        public long Id { get; set;}
        [Required]
        public Guid Guid { get; set;}
    }
	[Alias("TypeWithEnum")]
	[Schema("dbo")]
    public partial class TypeWithEnum : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public string EnumValue { get; set;}
    }
	[Alias("tab_OrderDetail")]
	[Schema("dbo")]
    public partial class tab_OrderDetail : IHasId<int> 
    {
        [Alias("col_Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int col_OrderId { get; set;}
        [Required]
        public int col_ProductId { get; set;}
        [Required]
        public decimal col_UnitPrice { get; set;}
        [Required]
        public int col_Quantity { get; set;}
        [Required]
        public decimal col_Discount { get; set;}
    }
	[Alias("T01")]
	[Schema("dbo")]
    public partial class T01 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("Attachment")]
	[Schema("dbo")]
    public partial class Attachment : IHasId<string> 
    {
        [Alias("Description")]
        [Required]
        public string Id { get; set;}
        public string FileName { get; set;}
        public string Type { get; set;}
        public byte[] Data { get; set;}
    }
	[Alias("TableName2")]
	[Schema("dbo")]
    public partial class TableName2 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public long Long { get; set;}
        [Required]
        public Guid Guid { get; set;}
    }
	[Alias("T02")]
	[Schema("dbo")]
    public partial class T02 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("ClassA")]
	[Schema("dbo")]
    public partial class ClassA : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string A { get; set;}
    }
	[Alias("TypeWithFlagsEnum")]
	[Schema("dbo")]
    public partial class TypeWithFlagsEnum : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int Flags { get; set;}
    }
	[Alias("T03")]
	[Schema("dbo")]
    public partial class T03 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("ClassB")]
	[Schema("dbo")]
    public partial class ClassB : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string ColumnB { get; set;}
    }
	[Alias("Table_for_datetime2_tests")]
	[Schema("dbo")]
    public partial class Table_for_datetime2_test : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public DateTime SomeDateTime { get; set;}
        public DateTime? ToVerifyPrecision { get; set;}
        public DateTime? NullableDateTimeLeaveItNull { get; set;}
    }
	[Alias("T04")]
	[Schema("dbo")]
    public partial class T04 : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("Employee")]
	[Schema("dbo")]
    public partial class Employee : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("Submission")]
	[Schema("dbo")]
    public partial class Submission : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public DateTime StoryDate { get; set;}
        public string Headline { get; set;}
        public string Body { get; set;}
    }
	[Alias("World")]
	[Schema("dbo")]
    public partial class World : IHasId<int> 
    {
        [Alias("id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int randomNumber { get; set;}
    }
	[Alias("ConfigSetting")]
	[Schema("dbo")]
    public partial class ConfigSetting : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        public string Value { get; set;}
    }
	[Alias("Group")]
	[Schema("dbo")]
    public partial class Group : IHasId<int> 
    {
        [Alias("GroupID")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
        public string ShortName { get; set;}
        [Required]
        public int GroupTypeID { get; set;}
        public string ContactDetails { get; set;}
        [Required]
        public DateTime BirthDay { get; set;}
    }
	[Alias("QO_Customer")]
	[Schema("dbo")]
    public partial class QO_Customer : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("PersonDescriptor")]
	[Schema("dbo")]
    public partial class PersonDescriptor : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string FirstName { get; set;}
        public string LastName { get; set;}
        [Required]
        public int Age { get; set;}
    }
	[Alias("QO_CustomerAddress")]
	[Schema("dbo")]
    public partial class QO_CustomerAddress : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int QO_CustomerId { get; set;}
        public string AddressLine1 { get; set;}
        public string AddressLine2 { get; set;}
        public string City { get; set;}
        public string State { get; set;}
        public string Country { get; set;}
    }
	[Alias("ProductWithManufacturer")]
	[Schema("dbo")]
    public partial class ProductWithManufacturer : IHasId<Guid> 
    {
        [Alias("ProductId")]
        [Required]
        public Guid Id { get; set;}
        public string ProductName { get; set;}
        [Required]
        public Guid fkManufacturerId { get; set;}
        public string ManufacturerName { get; set;}
    }
	[Alias("HasDateTimeOffsetMemeber")]
	[Schema("dbo")]
    public partial class HasDateTimeOffsetMemeber : IHasId<DateTimeOffset> 
    {
        [Alias("MomentInTime")]
        [Required]
        public DateTimeOffset Id { get; set;}
    }
	[Alias("Rockstar")]
	[Schema("dbo")]
    public partial class Rockstar : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public string FirstName { get; set;}
        public string LastName { get; set;}
        public int? Age { get; set;}
    }
	[Alias("DynamicCacheEntry")]
	[Schema("dbo")]
    public partial class DynamicCacheEntry : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        public string Data { get; set;}
        public DateTime? ExpiryDate { get; set;}
        [Required]
        public DateTime CreatedDate { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
	[Alias("FooCustomer")]
	[Schema("dbo")]
    public partial class FooCustomer : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("HasNullableDateTimeOffsetMemeber")]
	[Schema("dbo")]
    public partial class HasNullableDateTimeOffsetMemeber : IHasId<DateTimeOffset> 
    {
        [Alias("MomentInTime")]
        [Required]
        public DateTimeOffset Id { get; set;}
    }
	[Alias("RockstarAlbum")]
	[Schema("dbo")]
    public partial class RockstarAlbum : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int RockstarId { get; set;}
        public string Name { get; set;}
    }
	[Alias("CacheEntry")]
	[Schema("dbo")]
    public partial class CacheEntry : IHasId<string> 
    {
        [Alias("Id")]
        [Required]
        public string Id { get; set;}
        public string Data { get; set;}
        public DateTime? ExpiryDate { get; set;}
        [Required]
        public DateTime CreatedDate { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
	[Alias("OrderBlob")]
	[Schema("dbo")]
    public partial class OrderBlob : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Customer { get; set;}
        public string Employee { get; set;}
        public DateTime? OrderDate { get; set;}
        public DateTime? RequiredDate { get; set;}
        public DateTime? ShippedDate { get; set;}
        public int? ShipVia { get; set;}
        [Required]
        public decimal Freight { get; set;}
        public string ShipName { get; set;}
        public string ShipAddress { get; set;}
        public string ShipCity { get; set;}
        public string ShipRegion { get; set;}
        public string ShipPostalCode { get; set;}
        public string ShipCountry { get; set;}
        public string OrderDetails { get; set;}
        public string IntIds { get; set;}
        public string CharMap { get; set;}
    }
	[Alias("BarCustomerAddress")]
	[Schema("dbo")]
    public partial class BarCustomerAddress : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int BarCustomerId { get; set;}
        public string AddressLine1 { get; set;}
        public string AddressLine2 { get; set;}
        public string City { get; set;}
        public string State { get; set;}
        public string Country { get; set;}
    }
	[Alias("USERPROFILES")]
	[Schema("dbo")]
    public partial class USERPROFILE : IHasId<decimal> 
    {
        [Alias("USERPROFILEID")]
        [Required]
        public decimal Id { get; set;}
        [Required]
        public decimal PROFILEID { get; set;}
        [Required]
        public string USER_ID { get; set;}
        [Required]
        public decimal ISPRIMARY { get; set;}
    }
	[Alias("TypeWithByteArrayField")]
	[Schema("dbo")]
    public partial class TypeWithByteArrayField : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        public byte[] Content { get; set;}
    }
	[Alias("SelfCustomerAddress")]
	[Schema("dbo")]
    public partial class SelfCustomerAddress : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string AddressLine1 { get; set;}
        public string AddressLine2 { get; set;}
        public string City { get; set;}
        public string State { get; set;}
        public string Country { get; set;}
    }
	[Alias("Target")]
	[Schema("dbo")]
    public partial class Target : IHasId<int> 
    {
        public string Name { get; set;}
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
    }
	[Alias("MultiSelfCustomer")]
	[Schema("dbo")]
    public partial class MultiSelfCustomer : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
        public int? HomeAddressId { get; set;}
        public int? WorkAddressId { get; set;}
    }
	[Alias("LetterFrequency")]
	[Schema("dbo")]
    public partial class LetterFrequency : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Letter { get; set;}
    }
	[Alias("LetterWeighting")]
	[Schema("dbo")]
    public partial class LetterWeighting : IHasId<long> 
    {
        [Alias("LetterFrequencyId")]
        [Required]
        public long Id { get; set;}
        [Required]
        public int Weighting { get; set;}
    }
	[Alias("ModelWithDifferentNumTypes")]
	[Schema("dbo")]
    public partial class ModelWithDifferentNumType : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int Short { get; set;}
        [Required]
        public int Int { get; set;}
        [Required]
        public long Long { get; set;}
        [Required]
        public double Float { get; set;}
        [Required]
        public double Double { get; set;}
        [Required]
        public decimal Decimal { get; set;}
    }
	[Alias("ModelWithPreDropSql")]
	[Schema("dbo")]
    public partial class ModelWithPreDropSql : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("SelfCustomer")]
	[Schema("dbo")]
    public partial class SelfCustomer : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
        public int? SelfCustomerAddressId { get; set;}
    }
	[Alias("Foo")]
	[Schema("dbo")]
    public partial class Foo : IHasId<string> 
    {
        [Alias("SOME_COLUMN_NAME")]
        [Required]
        public string Id { get; set;}
    }
	[Alias("Point")]
	[Schema("dbo")]
    public partial class Point : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int Width { get; set;}
        [Required]
        public double Height { get; set;}
        [Required]
        public double Top { get; set;}
        [Required]
        public decimal Left { get; set;}
    }
	[Alias("Table1")]
	[Schema("dbo")]
    public partial class Table1 : IHasId<int> 
    {
        [Alias("Key")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Ena { get; set;}
    }
	[Alias("TheModelWithAliasedRowVersion")]
	[Schema("dbo")]
    public partial class TheModelWithAliasedRowVersion : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set;}
        public string Text { get; set;}
        [Required]
        public long TheVersion { get; set;}
    }
	[Alias("Q_CustomerAddress")]
	[Schema("dbo")]
    public partial class Q_CustomerAddress : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int Q_CustomerId { get; set;}
        public string AddressLine1 { get; set;}
        public string AddressLine2 { get; set;}
        public string City { get; set;}
        public string State { get; set;}
        public string Country { get; set;}
    }
	[Alias("Poco")]
	[Schema("dbo")]
    public partial class Poco : IHasId<string> 
    {
        [Alias("Name")]
        [Required]
        public string Id { get; set;}
    }
	[Alias("Bar")]
	[Schema("dbo")]
    public partial class Bar : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Baz { get; set;}
    }
	[Alias("SchemaWithRowVersion")]
	[Schema("Schema")]
    public partial class SchemaWithRowVersion : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        public string RandomStringProperty { get; set;}
        [Required]
        public byte[] RowVersion { get; set;}
    }
	[Alias("Section")]
	[Schema("Schema")]
    public partial class Section : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int ReportSectionId { get; set;}
        public string Name { get; set;}
        [Required]
        public decimal ReportId { get; set;}
    }
	[Alias("PageAlias")]
	[Schema("Schema")]
    public partial class PageAlias : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int ReportSectionIdAlias { get; set;}
        [Required]
        public int SectionIdAlias { get; set;}
    }
	[Alias("Page")]
	[Schema("Schema")]
    public partial class Page : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int SectionId { get; set;}
        [Required]
        public int ReportSectionId { get; set;}
    }
	[Alias("SectionAlias")]
	[Schema("Schema")]
    public partial class SectionAlias : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int ReportSectionIdAlias { get; set;}
        public string NameAlias { get; set;}
        [Required]
        public int ReportIdAlias { get; set;}
    }
	[Alias("ReportSections")]
	[Schema("MicroSite")]
    public partial class ReportSection : IHasId<int> 
    {
        [Alias("ReportSectionID")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
        [Required]
        public int ReportID { get; set;}
    }
	[Alias("ReportPages")]
	[Schema("MicroSite")]
    public partial class ReportPage : IHasId<int> 
    {
        [Required]
        public int AccessLevel { get; set;}
        [Required]
        public int AssignedEmployeeId { get; set;}
        [Required]
        public bool Cover { get; set;}
        [Required]
        public bool Deleted { get; set;}
        [Required]
        public bool Disabled { get; set;}
        [Alias("ReportPageID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int Index { get; set;}
        public string Name { get; set;}
        [Required]
        public int ReportSectionID { get; set;}
        public string Template { get; set;}
    }
	[Alias("LogEntries")]
	[Schema("MicroSite")]
    public partial class LogEntry : IHasId<int> 
    {
        [Required]
        public DateTime Date { get; set;}
        [Alias("LogEntriesID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int KlasId { get; set;}
        [Required]
        public int PageTrackerId { get; set;}
        [Required]
        public int ReportID { get; set;}
        [Required]
        public int ReportPageID { get; set;}
        public string RequestUrl { get; set;}
        [Required]
        public int Type { get; set;}
    }
	[Alias("Reports")]
	[Schema("MicroSite")]
    public partial class Report : IHasId<int> 
    {
        [Required]
        public int DefaultAccessLevel { get; set;}
        [Required]
        public bool Deleted { get; set;}
        public string Description { get; set;}
        [Alias("ReportID")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
    }
	[Alias("EditableRevisions")]
	[Schema("MicroSite")]
    public partial class EditableRevision : IHasId<int> 
    {
        public string Content { get; set;}
        [Required]
        public DateTime Date { get; set;}
        [Required]
        public int EditableID { get; set;}
        [Required]
        public int EmployeeId { get; set;}
        [Alias("EditableRevisionsID")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Reason { get; set;}
        public string Styles { get; set;}
    }
	[Alias("Editables")]
	[Schema("MicroSite")]
    public partial class Editable : IHasId<int> 
    {
        public string Content { get; set;}
        [Alias("EditableID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int Index { get; set;}
        [Required]
        public int ReportPageID { get; set;}
        public string Styles { get; set;}
        [Required]
        public int Type { get; set;}
    }
}
#pragma warning restore 1591


